"""
Tests for the report generation module.
"""

from datetime import datetime
from unittest.mock import Mock, patch

import pytest

from tirajira.processing.report_generator import ReportGenerator


def test_report_generator_initialization():
    """Test: report generator initialization."""
    # Create report generator
    report_generator = ReportGenerator()

    # Check that the logger was initialized
    assert report_generator.logger is not None


@patch("tirajira.processing.report_generator.get_logger")
@patch("tirajira.processing.report_generator.create_report_writer")
@patch("tirajira.processing.report_generator.datetime")
def test_generate_report_auto_filename(
    mock_datetime, mock_create_report_writer, mock_get_logger
):
    """Test: automatic report file name generation."""
    # Mock logger so it doesn't output to console
    mock_logger_instance = Mock()
    mock_get_logger.return_value = mock_logger_instance

    # Setup mock time
    fixed_time = datetime(2023, 12, 1, 12, 0, 0)
    mock_datetime.now.return_value = fixed_time

    # Create mocks
    mock_writer = Mock()
    mock_create_report_writer.return_value = mock_writer

    # Create report generator
    report_generator = ReportGenerator()

    # Data for report
    processing_details = [
        {
            "id": 0,
            "status": "success",
            "issue_key": "PROJ-123",
        },
    ]

    # Call the report generation method with automatic file name
    report_generator.generate_report(
        source_file="tasks.json",
        processing_details=processing_details,
        report_file=True,  # Automatic file name
        successful_count=1,
        total_count=1,
    )

    # Check that create_report_writer was called with the correct argument
    mock_create_report_writer.assert_called_once_with("json")

    # Check that writer.write_report was called with the correct file path
    call_args = mock_writer.write_report.call_args[0]
    report_data = call_args[0]
    file_path = call_args[1]

    assert file_path == "tirajira_report_20231201_120000.json"
    assert report_data["metadata"]["source_file"] == "tasks.json"
    assert report_data["metadata"]["total_tasks"] == 1
    assert report_data["metadata"]["successful_tasks"] == 1
    assert report_data["metadata"]["failed_tasks"] == 0
    assert len(report_data["tasks"]) == 1
    assert report_data["tasks"][0]["issue_key"] == "PROJ-123"

    # Check that the generated_at field contains the correct timestamp
    # We can't check the exact value since it's generated by datetime.now().isoformat()
    assert "generated_at" in report_data["metadata"]


@patch("tirajira.processing.report_generator.create_report_writer")
@patch("tirajira.processing.report_generator.get_logger")
def test_generate_report_no_save(mock_get_logger, mock_create_report_writer):
    """Test: do not save report (report_file=None)."""
    # Mock logger so it doesn't output to console
    mock_logger_instance = Mock()
    mock_get_logger.return_value = mock_logger_instance

    # Create mocks
    mock_writer = Mock()
    mock_create_report_writer.return_value = mock_writer

    # Create report generator
    report_generator = ReportGenerator()

    # Data for report
    processing_details = [
        {
            "id": 0,
            "status": "success",
            "issue_key": "PROJ-123",
        },
    ]

    # Call the report generation method without saving
    report_generator.generate_report(
        source_file="tasks.json",
        processing_details=processing_details,
        report_file=None,  # Do not save report
        successful_count=1,
        total_count=1,
    )

    # Check that create_report_writer was not called
    mock_create_report_writer.assert_not_called()

    # Check that writer.write_report was not called
    mock_writer.write_report.assert_not_called()


@patch("tirajira.processing.report_generator.get_logger")
@patch("tirajira.processing.report_generator.create_report_writer")
@patch("tirajira.processing.report_generator.datetime")
def test_generate_report_unsupported_format(
    mock_datetime, mock_create_report_writer, mock_get_logger
):
    """Test: report generation in unsupported format (should use JSON)."""
    # Mock logger so it doesn't output to console
    mock_logger_instance = Mock()
    mock_get_logger.return_value = mock_logger_instance

    # Setup mock time
    fixed_time = datetime(2023, 12, 1, 12, 0, 0)
    mock_datetime.now.return_value = fixed_time

    # Create mocks
    mock_writer = Mock()
    mock_create_report_writer.return_value = mock_writer

    # Create report generator
    report_generator = ReportGenerator()

    # Data for report
    processing_details = [
        {
            "id": 0,
            "status": "success",
            "issue_key": "PROJ-123",
        },
    ]

    # Call the report generation method in unsupported format
    report_generator.generate_report(
        source_file="tasks.json",
        processing_details=processing_details,
        report_file="report.unsupported",  # Unsupported format
        successful_count=1,
        total_count=1,
    )

    # Check that create_report_writer was called with JSON format
    mock_create_report_writer.assert_called_once_with("json")

    # Check that writer.write_report was called with the correct file path
    call_args = mock_writer.write_report.call_args[0]
    report_data = call_args[0]
    file_path = call_args[1]

    assert file_path == "report.unsupported"
    assert report_data["metadata"]["source_file"] == "tasks.json"
    assert report_data["metadata"]["total_tasks"] == 1
    assert report_data["metadata"]["successful_tasks"] == 1
    assert report_data["metadata"]["failed_tasks"] == 0
    assert len(report_data["tasks"]) == 1
    assert report_data["tasks"][0]["issue_key"] == "PROJ-123"

    # Check that the generated_at field contains the correct timestamp
    # We can't check the exact value since it's generated by datetime.now().isoformat()
    assert "generated_at" in report_data["metadata"]


@patch("tirajira.processing.report_generator.get_logger")
@patch("tirajira.processing.report_generator.create_report_writer")
@patch("tirajira.processing.report_generator.datetime")
def test_generate_report_no_extension(
    mock_datetime, mock_create_report_writer, mock_get_logger
):
    """Test: report generation without extension in filename (should add .json)."""
    # Mock logger so it doesn't output to console
    mock_logger_instance = Mock()
    mock_get_logger.return_value = mock_logger_instance

    # Setup mock time
    fixed_time = datetime(2023, 12, 1, 12, 0, 0)
    mock_datetime.now.return_value = fixed_time

    # Create mocks
    mock_writer = Mock()
    mock_create_report_writer.return_value = mock_writer

    # Create report generator
    report_generator = ReportGenerator()

    # Data for report
    processing_details = [
        {
            "id": 0,
            "status": "success",
            "issue_key": "PROJ-123",
        },
    ]

    # Call the report generation method without extension in filename
    report_generator.generate_report(
        source_file="tasks.json",
        processing_details=processing_details,
        report_file="report_without_extension",  # Without extension
        successful_count=1,
        total_count=1,
    )

    # Check that create_report_writer was called with JSON format
    mock_create_report_writer.assert_called_once_with("json")

    # Check that writer.write_report was called with the correct file path
    call_args = mock_writer.write_report.call_args[0]
    report_data = call_args[0]
    file_path = call_args[1]

    assert file_path == "report_without_extension"
    assert report_data["metadata"]["source_file"] == "tasks.json"
    assert report_data["metadata"]["total_tasks"] == 1
    assert report_data["metadata"]["successful_tasks"] == 1
    assert report_data["metadata"]["failed_tasks"] == 0
    assert len(report_data["tasks"]) == 1
    assert report_data["tasks"][0]["issue_key"] == "PROJ-123"

    # Check that the generated_at field contains the correct timestamp
    # We can't check the exact value since it's generated by datetime.now().isoformat()
    assert "generated_at" in report_data["metadata"]


@patch("tirajira.processing.report_generator.get_logger")
@patch("tirajira.processing.report_generator.create_report_writer")
@patch("tirajira.processing.report_generator.datetime")
def test_generate_report_with_issue_urls(
    mock_datetime, mock_create_report_writer, mock_get_logger
):
    """Test: report generation with adding Jira task URLs."""
    # Mock logger so it doesn't output to console
    mock_logger_instance = Mock()
    mock_get_logger.return_value = mock_logger_instance

    # Setup mock time
    fixed_time = datetime(2023, 12, 1, 12, 0, 0)
    mock_datetime.now.return_value = fixed_time

    # Create mocks
    mock_writer = Mock()
    mock_create_report_writer.return_value = mock_writer

    # Create report generator
    report_generator = ReportGenerator()

    # Data for report with tasks having keys
    processing_details = [
        {
            "id": 0,
            "status": "success",
            "issue_key": "PROJ-123",
        },
        {
            "id": 1,
            "status": "success",
            "issue_key": "PROJ-124",
        },
        {
            "id": 2,
            "status": "failed",
            # No issue_key for failed task
        },
    ]

    # Call the report generation method with Jira server specified
    report_generator.generate_report(
        source_file="tasks.json",
        processing_details=processing_details,
        report_file="report_with_urls.json",
        successful_count=2,
        total_count=3,
        jira_server="https://example.atlassian.net",
    )

    # Check that writer.write_report was called
    mock_writer.write_report.assert_called_once()

    # Check the report content
    call_args = mock_writer.write_report.call_args[0]
    report_data = call_args[0]
    tasks = report_data["tasks"]

    # Check that task URLs were added
    assert len(tasks) == 3
    assert tasks[0]["issue_key"] == "PROJ-123"
    assert tasks[0]["issue_url"] == "https://example.atlassian.net/browse/PROJ-123"
    assert tasks[1]["issue_key"] == "PROJ-124"
    assert tasks[1]["issue_url"] == "https://example.atlassian.net/browse/PROJ-124"

    # Check that URLs are added only for tasks with keys
    assert "issue_url" in tasks[0]
    assert "issue_url" in tasks[1]

    # Check that URL is not added for task without key
    assert "issue_key" not in tasks[2]
    assert "issue_url" not in tasks[2]


@patch("tirajira.processing.report_generator.get_logger")
@patch("tirajira.processing.report_generator.create_report_writer")
@patch("tirajira.processing.report_generator.datetime")
def test_generate_report_without_jira_server(
    mock_datetime, mock_create_report_writer, mock_get_logger
):
    """Test: report generation without specifying Jira server (do not add task URLs)."""
    # Mock logger so it doesn't output to console
    mock_logger_instance = Mock()
    mock_get_logger.return_value = mock_logger_instance

    # Setup mock time
    fixed_time = datetime(2023, 12, 1, 12, 0, 0)
    mock_datetime.now.return_value = fixed_time

    # Create mocks
    mock_writer = Mock()
    mock_create_report_writer.return_value = mock_writer

    # Create report generator
    report_generator = ReportGenerator()

    # Data for report
    processing_details = [
        {
            "id": 0,
            "status": "success",
            "issue_key": "PROJ-123",
        },
    ]

    # Call the report generation method without specifying Jira server
    report_generator.generate_report(
        source_file="tasks.json",
        processing_details=processing_details,
        report_file="report_without_urls.json",
        successful_count=1,
        total_count=1,
        # jira_server not specified
    )

    # Check that writer.write_report was called
    mock_writer.write_report.assert_called_once()

    # Check the report content
    call_args = mock_writer.write_report.call_args[0]
    report_data = call_args[0]
    tasks = report_data["tasks"]

    # Check that task URLs were not added
    assert len(tasks) == 1
    assert tasks[0]["issue_key"] == "PROJ-123"
    assert "issue_url" not in tasks[0]  # URL should not be added


@patch("tirajira.processing.report_generator.create_report_writer")
@patch("tirajira.processing.report_generator.get_logger")
def test_generate_report_exception_handling(mock_get_logger, mock_create_report_writer):
    """Test: exception handling during report generation."""
    # Create mocks
    mock_logger = Mock()
    mock_get_logger.return_value = mock_logger
    mock_create_report_writer.side_effect = Exception("Error creating report")

    # Create report generator
    report_generator = ReportGenerator()

    # Data for report
    processing_details = [
        {
            "id": 0,
            "status": "success",
            "issue_key": "PROJ-123",
        },
    ]

    # Call the report generation method
    report_generator.generate_report(
        source_file="tasks.json",
        processing_details=processing_details,
        report_file="report.json",
        successful_count=1,
        total_count=1,
    )

    # Check that the logger recorded the error
    mock_logger.error.assert_called_once()
    error_call = mock_logger.error.call_args[0][0]
    assert "Error saving report" in error_call


if __name__ == "__main__":
    pytest.main([__file__])
